# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c083cc90e621c0087ceed2c01d8067110f1881b5993f4a3d9e6f0effee33bc106fb92246723d8f7ba9c4915152a2f77c5517b2407a4bd0fe8d00e9c6b8b0dad7

test:
  secret_key_base: cbdf87644a3a05be4ebcf7511fc60779febd2218e265e6350cb0c7d14050902dea5ae66d7f555b3e3490dfc6c25d372335a8303d52063f9316575d66548dec00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
